# Generated by Django 2.0.3 on 2018-03-18 13:20

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miniuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniuser',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='miniuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='email',
            field=models.EmailField(blank=True, default=None, error_messages={'unique': 'This mail address is already in use....'}, max_length=508, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
