# Generated by Django 2.0.3 on 2018-03-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniuser', '0002_simplified_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
